apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sharing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-sharing
  template:
    metadata:
      labels:
        app: data-sharing
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do echo $(date) >> /data/shared-file.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-data
          mountPath: /data
      - name: multitool
        image: wbitt/network-multitool
        command: ["sh", "-c", "tail -f /data/shared-file.txt"]
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: local-pvc
